@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LM LOGIC_COLOR
participant ":AddressBookParser" as ABP LOGIC_COLOR
participant ":DeleteTagFromEventCommandParser" as DTCP LOGIC_COLOR
participant "cmd:DeleteTagFromEventCommand" as DTC LOGIC_COLOR
participant "r:CommandResult" as CR LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LM : execute("deleteEventTag 1 t/Important")
activate LM
LM -> ABP : parseCommand("deleteEventTag 1 t/Important")
activate ABP
create DTCP
ABP -> DTCP : parse("deleteEventTag 1 t/Important")
activate DTCP
DTCP --> ABP : DeleteTagFromEventCommand
deactivate DTCP
ABP --> LM : DeleteTagFromEventCommand
deactivate ABP

LM -> DTC : execute(Model)
activate DTC
DTC -> Model : updateEvent(event, updated)
activate Model
Model --> DTC : event updated
deactivate Model
DTC --> LM : CommandResult
deactivate DTC
LM --> CR : return result
deactivate LM
@enduml
