@startuml
!include style.puml
skinparam ArrowFontStyle plain
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindAddressCommandParser" as FACP LOGIC_COLOR
participant "p:AddressContainsKeywordsAsSubstringPredicate" as Predicate LOGIC_COLOR
participant "f:FindAddressCommand" as FAC LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box
box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findAddress Clementi Avenue 3")
activate LogicManager
LogicManager -> AddressBookParser : parseCommand("findAddress Clementi Avenue 3")
activate AddressBookParser

create FACP
AddressBookParser -> FACP
activate FACP
FACP --> AddressBookParser
deactivate FACP

AddressBookParser -> FACP : parse("Clementi Avenue 3")
activate FACP

create Predicate
FACP -> Predicate : new AddressContainsKeywordsAsSubstringPredicate(["Clementi", "Avenue", "3"])
activate Predicate
Predicate --> FACP : p
deactivate Predicate

create FAC
FACP -> FAC : new FindAddressCommand(p)
activate FAC
FAC --> FACP : f
deactivate FAC

FACP --> AddressBookParser : f
deactivate FACP
'Hidden arrow to position the destroy marker below the end of the activation bar.
FACP -[hidden]-> AddressBookParser
destroy FACP

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FAC : execute(m)
activate FAC
FAC -> Model : updateFilteredPersonList(p)
activate Model
Model --> FAC
deactivate Model

create CommandResult
FAC -> CommandResult
activate CommandResult
CommandResult --> FAC : r
deactivate CommandResult

FAC --> LogicManager : r
deactivate FAC

[<--LogicManager
deactivate LogicManager
@enduml
