@startuml
!include style.puml
skinparam classBackgroundColor RELATIONSHIP_COLOR

class Relationship {
  + {static} MESSAGE_CONSTRAINTS : String
  + {static} VALIDATION_REGEX : String
  - firstUserId : String
  - secondUserId : String
  - forwardName : String
  - reverseName : String
  - tags : Set<Tag>

  + Relationship(user1Id : String, user2Id : String, forwardName : String, reverseName : String, tags : Set<Tag>)
  + {static} isValidRelationshipName(test : String) : boolean
  + getFirstUserId() : String
  + getSecondUserId() : String
  + getForwardName() : String
  + getReverseName() : String
  + getNameFromPerspective(userId : String) : String
  + getTags() : Set<Tag>
  + involvesUser(userId : String) : boolean
  + isSameRelationship(userId1 : String, userId2 : String, relationshipName : String) : boolean
  + isSameRelationship(other : Relationship) : boolean
  + withAddedTag(tag : Tag) : Relationship
  + withRemovedTag(tag : Tag) : Relationship
  + equals(other : Object) : boolean
  + hashCode() : int
  + toString() : String
}

class Tag {
  + tagName : String
}

Relationship "1" -- "1" Tag : contains >
Relationship "1" -- "1" firstUserId :  User 1 >
Relationship "1" -- "1" secondUserId : User 2 >
Relationship "1" -- "1" forwardName : Name from User 1 to User 2 >
Relationship "1" -- "1" reverseName : Name from User 2 to User 1 >
@enduml
