@startuml
!include style.puml
skinparam ArrowFontStyle plain

box "Logic" LOGIC_COLOR_T1
participant ":LogicManager" as LM LOGIC_COLOR
participant ":AddressBookParser" as ABP LOGIC_COLOR
participant ":UpdateEventDateCommandParser" as UEDCP LOGIC_COLOR
participant "cmd:UpdateEventDateCommand" as UEDC LOGIC_COLOR
participant "r:CommandResult" as CR LOGIC_COLOR
end box

box "Model" MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LM : execute("updateEventDate 1 d/2025-03-15T09:30")
activate LM
LM -> ABP : parseCommand("updateEventDate 1 d/2025-03-15T09:30")
activate ABP
create UEDCP
ABP -> UEDCP : parse("updateEventDate 1 d/2025-03-15T09:30")
activate UEDCP
UEDCP --> ABP : UpdateEventDateCommand
deactivate UEDCP
ABP --> LM : UpdateEventDateCommand
deactivate ABP

LM -> UEDC : execute(Model)
activate UEDC
UEDC -> Model : updateEvent(original, updated)
activate Model
Model --> UEDC : event updated
deactivate Model
UEDC --> LM : CommandResult
deactivate UEDC
LM --> CR : return result
deactivate LM
@enduml
